services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: broncofit-backend:latest
    environment:
      - NODE_ENV=production
      - PORT=3001
    expose:
      - "3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: broncofit-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certs:/etc/letsencrypt
      - webroot:/var/www/certbot
    depends_on:
      - backend

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certs:/etc/letsencrypt
      - webroot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # To manually request certificates, run:
    # docker-compose run --rm certbot certonly --webroot -w /var/www/certbot \
    #   -d bronco.fit -d www.bronco.fit --email you@example.com --agree-tos --no-eff-email

volumes:
  certs:
  webroot: