services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: broncofit-backend:latest
    environment:
      - NODE_ENV=production
      - PORT=3001
    expose:
      - "3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: broncofit-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certs:/etc/letsencrypt
      - webroot:/var/www/certbot
    depends_on:
      - backend

  certbot:
    build:
      context: ./proxy/certbot
      dockerfile: Dockerfile
    image: broncofit-certbot:latest
    volumes:
      - certs:/etc/letsencrypt
      - webroot:/var/www/certbot
      - ./proxy/godaddy.ini:/secrets/godaddy.ini:ro
    entrypoint: ""
    # Use interactive/run commands to issue or renew certificates with the GoDaddy DNS plugin:
    # Example to request a wildcard and domain cert:
    # docker-compose run --rm certbot certonly --dns-godaddy --dns-godaddy-credentials /secrets/godaddy.ini \
    #   -d bronco.fit -d '*.bronco.fit' --email you@example.com --agree-tos --no-eff-email

volumes:
  certs:
  webroot: